######################################################################
# Automatically generated by qmake (3.1) Thu Dec 2 15:50:10 2021
######################################################################

TEMPLATE = app
CONFIG += console
QT += core

SOURCES = \
	src/main.cpp \
	src/task_manager.cpp

HEADERS = \
	include/task_manager.h

TARGET = prog

release: DESTDIR = build
release: OBJECTS_DIR = build/.obj
release: MOC_DIR = build/.moc

# Directories
