SRC_PATH=src/
all:
	g++ -Wall -std=c++1z -Ofast -o slow $(SRC_PATH)main1.cpp $(SRC_PATH)slow_multiplication.cpp
	g++ -Wall -std=c++1z -Ofast -o fast $(SRC_PATH)main2.cpp $(SRC_PATH)fast_multiplication.cpp
